---
title: "prac15"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1 

```{r prac 15}
countsa <- c(3, 1, 1, 3, 1, 4, 3, 2, 0, 5, 0, 4, 2)

pois.ll <- function(lambda) { -sum(dpois(countsa, lambda, log = TRUE))
}

mean(countsa)
loglike <- optim(par=1, ## starting value
      fn=pois.ll,## need to specify for 1-D optimization
      lower=0.001, upper=10)
loglike
lamda_est <- loglike$par
lamda_est
set.seed(0)




optim(par = 5, fn = pois.ll,
      method="L-BFGS-B",
      lower = 0.0001,
      upper=Inf)


fit <- glm(countsa ~ 1, family = poisson())
fit

MASS::fitdistr(countsa,'Poisson')

nlm(pois.ll,0.5)

```

## Question 2

```{r newtons}
nr.poi=function(x=countsa,t=10,iter=5)
{
  x=countsa
  x.mean=mean(x)
  par.hat=matrix(0,1,1)
  estimate=c(rep(NULL,iter+1))
  difference=c(rep(NULL,iter+1))
  estimate[1]=t
  difference[1]=abs(t-x.mean)
  for(i in 1:iter)
  {
    #First partial derivative of log-likelihood function with respect to mu
    dbt=(exp(-t) * (t^((x) - 1) * (x)) - exp(-t) * (t^(x)))/factorial(x)/(exp(-t) * 
    (t^(x))/factorial(x))
    
    #Second partial derivative of log-likelihood function with respect to mu, then mu
    dbtt=(exp(-t) * (t^(((x) - 1) - 1) * ((x) - 1) * (x)) - exp(-t) * 
    (t^((x) - 1) * (x)) - (exp(-t) * (t^((x) - 1) * (x)) - exp(-t) * 
    (t^(x))))/factorial(x)/(exp(-t) * (t^(x))/factorial(x)) - 
    (exp(-t) * (t^((x) - 1) * (x)) - exp(-t) * (t^(x)))/factorial(x) * 
        ((exp(-t) * (t^((x) - 1) * (x)) - exp(-t) * (t^(x)))/factorial(x))/(exp(-t) * 
        (t^(x))/factorial(x))^2
    
    sdbt=sum(dbt)
    sdbtt=sum(dbtt)
    
    #hessian matrix
    h=matrix(sdbtt,1,1)
    
    #gradient vector
    g=matrix(sdbt,1,1)
    
    #parameter
    par=matrix(t,1,1)
    par.hat=par-solve(h)%*%g
    t=par.hat[1,]
    estimate[i+1]=t
    difference[i+1]=t-x.mean
  }
  tabel=data.frame(estimate,difference)
  rownames(tabel)=(c("Initiation",1:iter))
  print(x)
  print(tabel)
  cat("The real MLE value for mu is :",x.mean,"\n")
  cat("The approximated MLE value for mu is",t,"\n")
  return(tabel)
}

table <- nr.poi()
plot(seq_len(6),y = table[,1] ,lty = 1,type = 'b',pch = 15,col = 'green', main='estimate and difference of loglikelihood with respect to possion count vector',xlab = 'estimated and difference',ylab = 'Initalization')
lines(seq_len(6),y = table[,2] , col = 'red',lwd = 1, pch = 19, type = 'b' )
legend('bottomright',c("estimate","difference"), lwd=c(5,2), col=c("green","red"), y.intersp=1.5, pch = c(15,19))
```

